# Generated by Django 2.2.5 on 2020-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200228_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket',
            field=models.IntegerField(),
        ),
    ]
