# Generated by Django 2.2.5 on 2020-03-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200303_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
