# Generated by Django 2.2.5 on 2020-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200303_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(default=None, related_name='followed_by', to='events.Profile'),
        ),
    ]
