# Generated by Django 2.2.5 on 2020-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200304_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='button',
            field=models.BooleanField(default=False),
        ),
    ]
