# Generated by Django 2.2.5 on 2020-03-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_userfollowing_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='button',
        ),
    ]
